#!/bin/bash

#  Downloads, installs (if needed) and runs dynamo locally

# obtained from here https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
DYNAMO_URL=https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz

DIR=$HOME/src/dynamodb
JAR=$DIR/DynamoDBLocal.jar


install_dynamo() {

   mkdir -p $DIR

   FILE="dynamodb_local_latest"
   curl $DYNAMO_URL > $DIR/$FILE.tar.gz
   gunzip $DIR/$FILE.tar.gz
   tar -xvf $DIR/$FILE.tar -C $DIR

}

if [ ! -f $JAR ]; then
  install_dynamo
fi

java -Djava.library.path=$DIR/DynamoDBLocal_lib -jar $JAR -sharedDb