package com.github.restup.mapping.fields.composition;

class BasicIdentifier implements Identifier {

	private static Identifier TRUE;
	private static Identifier FALSE;

    private final boolean nonAutoGeneratedValuePermitted;

    BasicIdentifier(boolean nonAutoGeneratedValuePermitted) {
        this.nonAutoGeneratedValuePermitted = nonAutoGeneratedValuePermitted;
    }

    public boolean isNonAutoGeneratedValuePermitted() {
        return nonAutoGeneratedValuePermitted;
    }

	public static Identifier of(boolean nonAutoGeneratedValuePermitted) {
		if ( nonAutoGeneratedValuePermitted ) {
			if ( TRUE == null ) {
				synchronized (BasicIdentifier.class) {
					TRUE = new BasicIdentifier(nonAutoGeneratedValuePermitted);
				}
			}
			return TRUE;
		}
		if ( FALSE == null ) {
			synchronized (BasicIdentifier.class) {
				FALSE = new BasicIdentifier(nonAutoGeneratedValuePermitted);
			}
		}
		return FALSE;
	}
    
}
