package com.github.restup.mapping.fields.composition;

public interface Identifier {

    public static Builder builder() {
        return new Builder();
    }

    boolean isNonAutoGeneratedValuePermitted();

    static class Builder {

        private boolean nonAutoGeneratedValuePermitted;

        private Builder me() {
            return this;
        }

        public Builder nonAutoGeneratedValuePermitted(boolean nonAutoGeneratedValuePermitted) {
            this.nonAutoGeneratedValuePermitted = nonAutoGeneratedValuePermitted;
            return me();
        }

        public Identifier build() {
            return BasicIdentifier.of(nonAutoGeneratedValuePermitted);
        }
    }

}
