package com.github.restup.mapping.fields.composition;

import static org.junit.Assert.assertEquals;
import org.junit.Test;

public class IdentifierTest {

    
    @Test
    public void testBuilder() {
        testBuilder(true);
        testBuilder(false);
    }
    
    private void testBuilder(boolean nonAutoGeneratedValuePermitted) {
        assertEquals(nonAutoGeneratedValuePermitted, Identifier.builder().nonAutoGeneratedValuePermitted(nonAutoGeneratedValuePermitted).build().isNonAutoGeneratedValuePermitted());        
    }
    
}
